AWSTemplateFormatVersion: 2010-09-09
Description: create to AZ
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCID
          - SubnetId
          - SecurityGroupID
    ParameterLabels: 
      VPCID: 
        default: "Which VPC should this be deployed to?"

Parameters: 
  SubnetPrivateCidrBlock:
    Type: String
    Default: ''
  VpcCidr:
    Type: String
    Default: ''
#Mappings: 

#Conditions: 

Resources: 
  # Create to VPC
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: "test vpc"
  # Subnet
  SubnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetPrivateCidrBlock
      VpcId: !Ref VPC
#Outputs: