AWSTemplateFormatVersion: 2010-09-09
Description: create to RDS
##########################################
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'Infomation'
        Parameters: 
          - AvailabilityZone
          - SubnetId1
          - SubnetId2
          - RDSServerName
          - RDSServerPort

Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a

  SubnetId1:
    Type: AWS::EC2::Subnet::Id

  SubnetId2:
    Type: AWS::EC2::Subnet::Id
  
  RDSServerName:
    Type: String
    Description: "RDS Servername specifed"
  
  RDSServerPort:
    Type: String
    Description: "RDS ServerPort specifed"

Resources:
  DMSVPCRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - dms.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole
      Path: "/"
      RoleName: dms-vpc-role
      Tags:
        - Key: Description
          Value: !Sub CreatedBy${AWS::StackName}

  ReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    DependsOn: DMSVPCRole
    Properties:
      ReplicationSubnetGroupIdentifier: dms-subnet-group
      ReplicationSubnetGroupDescription: DMS subnet group
      SubnetIds: 
        - !Ref SubnetId1
        - !Ref SubnetId2

  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    DependsOn: ReplicationSubnetGroup
    Properties: 
      AllocatedStorage: 5
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      AvailabilityZone: !Ref AvailabilityZone
      EngineVersion: 3.4.7
      # KmsKeyId: String
      MultiAZ: false
      # PreferredMaintenanceWindow: String
      PubliclyAccessible: false
      ReplicationInstanceClass: dms.t2.medium
      # ReplicationInstanceIdentifier: String
      ReplicationSubnetGroupIdentifier: !Ref ReplicationSubnetGroup
      # ResourceIdentifier: String
      # Tags: 
      #   - Tag
      # VpcSecurityGroupIds: 
      #   - String
  SourceSQLServerEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EngineName: sqlserver
      EndpointIdentifier: SourceRDSSQLServer
      EndpointType: source
      Username: !Ref AWS::StackName
      Password: !Ref AWS::StackName
      ServerName: !Ref RDSServerName
      Port: !Ref RDSServerPort
      DatabaseName: !Sub ${AWS::StackName}-dms
    
  # TargetPostgreSQLEndpoint:
  #   Type: AWS::DMS::Endpoint
  #   Properties:
  #     EngineName: sqlserver
  #     EndpointIdentifier: TargetRDSSQLServer
  #     EndpointType: target
  #     Username: root
  #     Password: Root1234
  #     ServerName:
  #       Fn::GetAtt: [ RDSPostgreSQL, Endpoint.Address ]
  #     Port:
  #       Fn::GetAtt: [ RDSPostgreSQL, Endpoint.Port ]
  #     DatabaseName: dms